
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 08 03:02:23 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POR = 14;
  public static final int GE = 31;
  public static final int ENTERO = 36;
  public static final int INT = 2;
  public static final int FOR = 7;
  public static final int CP = 21;
  public static final int EPSILON = 38;
  public static final int NOT = 27;
  public static final int AND = 34;
  public static final int IGUAL = 24;
  public static final int LT = 32;
  public static final int CL = 23;
  public static final int OR = 35;
  public static final int DIV = 15;
  public static final int UMENOS = 16;
  public static final int IF = 3;
  public static final int LE = 30;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 26;
  public static final int MENOS = 13;
  public static final int MOD = 17;
  public static final int NEQ = 29;
  public static final int IDENT = 37;
  public static final int EQ = 28;
  public static final int DMENOS = 19;
  public static final int ELSE = 4;
  public static final int TO = 8;
  public static final int WHILE = 6;
  public static final int DOWNTO = 9;
  public static final int DMAS = 18;
  public static final int AP = 20;
  public static final int GT = 33;
  public static final int PRINT = 11;
  public static final int DO = 5;
  public static final int STEP = 10;
  public static final int AL = 22;
  public static final int PYC = 25;
  public static final int MAS = 12;
}

