
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 06 18:02:48 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 26;
  public static final int MENOS = 9;
  public static final int LT = 24;
  public static final int IDENT = 29;
  public static final int ELSE = 3;
  public static final int CP = 14;
  public static final int PYC = 18;
  public static final int OR = 27;
  public static final int IGUAL = 17;
  public static final int CL = 16;
  public static final int WHILE = 5;
  public static final int NOT = 19;
  public static final int IF = 2;
  public static final int UMENOS = 12;
  public static final int GT = 25;
  public static final int LE = 22;
  public static final int POR = 10;
  public static final int AP = 13;
  public static final int DO = 4;
  public static final int AL = 15;
  public static final int EOF = 0;
  public static final int EPSILON = 30;
  public static final int DIV = 11;
  public static final int GE = 23;
  public static final int PRINT = 7;
  public static final int error = 1;
  public static final int EQ = 20;
  public static final int ENTERO = 28;
  public static final int FOR = 6;
  public static final int NEQ = 21;
  public static final int MAS = 8;
}

