
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 09 20:21:59 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CAMBIO = 23;
  public static final int POR = 17;
  public static final int CHAR = 3;
  public static final int GE = 35;
  public static final int ENTERO = 40;
  public static final int INT = 2;
  public static final int FOR = 10;
  public static final int CHARACTER = 41;
  public static final int CP = 25;
  public static final int EPSILON = 43;
  public static final int AND = 38;
  public static final int NOT = 31;
  public static final int LT = 36;
  public static final int IGUAL = 28;
  public static final int CL = 27;
  public static final int OR = 39;
  public static final int DIV = 18;
  public static final int IF = 6;
  public static final int UMENOS = 19;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int MENOS = 16;
  public static final int MOD = 20;
  public static final int NEQ = 33;
  public static final int IDENT = 42;
  public static final int EQ = 32;
  public static final int DMENOS = 22;
  public static final int CINT = 5;
  public static final int ELSE = 7;
  public static final int TO = 11;
  public static final int CCHAR = 4;
  public static final int WHILE = 9;
  public static final int DOWNTO = 12;
  public static final int DMAS = 21;
  public static final int GT = 37;
  public static final int AP = 24;
  public static final int PRINT = 14;
  public static final int DO = 8;
  public static final int STEP = 13;
  public static final int AL = 26;
  public static final int PYC = 29;
  public static final int MAS = 15;
}

