
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 15 14:07:42 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DP = 6;
  public static final int COMA = 5;
  public static final int DOUBLE = 3;
  public static final int error = 1;
  public static final int IDENT = 7;
  public static final int EOF = 0;
  public static final int PYC = 4;
  public static final int INT = 2;
}

