
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 06 16:51:51 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int A = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

