
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 08 15:26:45 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 30;
  public static final int MENOS = 27;
  public static final int AND = 22;
  public static final int IDENT = 34;
  public static final int CP = 6;
  public static final int PYC = 7;
  public static final int OR = 23;
  public static final int INT = 2;
  public static final int MENOSMENOS = 25;
  public static final int CL = 9;
  public static final int NOT = 17;
  public static final int MEQ = 16;
  public static final int CC = 11;
  public static final int POR = 28;
  public static final int AP = 5;
  public static final int AL = 8;
  public static final int COMA = 13;
  public static final int FLOAT = 3;
  public static final int EOF = 0;
  public static final int MAOQ = 20;
  public static final int DIV = 29;
  public static final int MASMAS = 24;
  public static final int AC = 10;
  public static final int NUMERO = 32;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int EQ = 18;
  public static final int MEOQ = 19;
  public static final int NUMEROF = 33;
  public static final int FOR = 14;
  public static final int NEQ = 21;
  public static final int ASIG = 12;
  public static final int MAS = 26;
  public static final int UMINUS = 31;
  public static final int MAQ = 15;
}

